### ISSUE TITLE
Unable to parse integers found in enums in unqork open api spec

### ISSUE THREAD

**Issue by upgradingdave** [camunda/connectors#2277]
__Describe the Bug__

When trying to parse [Unqork's open api spec](https://developers.unqork.io/api/1.0/openapi.yml), the following error is thrown: 

```
Generation failed: class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')
```

__Steps to Reproduce__

1. Run this: 

```
congen -e ServiceTask -e IntermediateThrowEvent generate openapi-outbound https://developers.unqork.io/api/1.0/openapi.yml
```

2. An exception is thrown because the `choice` variables refrenced [on this line here](https://github.com/camunda/connectors/blob/f55483bffd4ed0324e96c1e7109f9d3cd4e08275/element-template-generator/http-dsl/src/main/java/io/camunda/connector/generator/dsl/http/PropertyUtil.java#L323) are expected to be Strings. However, in Unqork open api spec, line 5709 has a definition like this: 

```
    SubmissionSortOrder:
      name: sortOrder
      in: query
      description: Order of sort, if `sortBy` is specified.  One of [`1` (ascending),`-1` (descending)]
      required: false
      schema:
        type: integer
        enum:
          - 1
          - -1
        default: 1
```

The `1` and `-1` are Integers and that's what causes the type cast exception

__Expected Behavior__

No error should be thrown and a valid json element template to be output.

__Environment__

- OS: MacOS Monterey (12.6.3)
- Library version: 8.5.0-SNAPSHOT
- Camunda version: N/A
