### ISSUE TITLE
AWS connector doesn't work with WebIdentity due to missing dependency

### ISSUE THREAD

**Issue by denpolischuk** [camunda/connectors#3754]
__Describe the Bug__
When running camunda connectors inside an AWS EKS cluster that uses IAM roles for service accounts (IRSA), cammunda-connectors can't assume the role through the web identity and falls back to the node role (using EC2 Metadata server) if there's one.

Given EKS k8s cluster with enabled IRSA.
1. Prepare IAM role to use with connector that has SQS policy and trusted relationship:
Name: `camunda-connector-role`
Policy
```json
{
    "Statement": [
        {
            "Action": [
                "sqs:ReceiveMessage",
                "sqs:GetQueueUrl",
                "sqs:GetQueueAttributes",
                "sqs:DeleteMessageBatch",
                "sqs:DeleteMessage",
                "sqs:ChangeMessageVisibilityBatch",
                "sqs:ChangeMessageVisibility"
            ],
            "Effect": "Allow",
            "Resource": "arn:aws:sqs:eu-central-1:111111111111:some-queue"
        }
    ],
    "Version": "2012-10-17"
}
```
Trusted relationship
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "TRForCamundaConnector",
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::111111111111:oidc-provider/oidc.eks.eu-central-1.amazonaws.com/id/CLUSTEROIDCID"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringLike": {
                    "oidc.eks.eu-central-1.amazonaws.com/id/CLUSTEROIDCID:sub": [
                        "system:serviceaccount:camunda-namespace:camunda-connector"
                    ]
                }
            }
        }
    ]
}
```
2. Prepare the `camunda/camunda-platform` helm chart values file:
  2.1 specify the role annotation on the camunda connector service account
```yaml
connectors:                                                                                                       
  enabled: true                                                                                                   
  serviceAccount:                                                                                                 
    enabled: true                                                                                                 
    annotations:                                                                                                  
      eks.amazonaws.com/role-arn: arn:aws:iam::111111111111:role/camunda-connector-role 
```
  2.2. To reproduce the error, make sure that, if you use node roles, the app won't get the node role credentials through the EC2 Metadata server. For that, add a dummy env variable to override the credentials endpoint to the helm chart values file
```yaml
env:                                             
  - name: AWS_CONTAINER_CREDENTIALS_RELATIVE_URI 
    value: "none"
```
2.3. Run the installation 
3. In camunda-connectors pod you should be able to see the error, that looks like this
```
i.c.c.r.i.e.BatchExecutableProcessor     : Failed to activate connector of type 'io.camunda:aws-sqs-inbound:1' with deduplication ID 'Listen-to-Intent-Created-ID', reason: Unable to load AWS credentials from any provider in the chain: 
[EnvironmentVariableCredentialsProvider: Unable to load AWS credentials from environment variables (AWS_ACCESS_KEY_ID (or AWS_ACCESS_KEY) and AWS_SECRET_KEY (or AWS_SECRET_ACCESS_KEY)),
SystemPropertiesCredentialsProvider: Unable to load AWS credentials from Java system properties (aws.accessKeyId and aws.secretKey),
WebIdentityTokenCredentialsProvider: To use assume role profiles the aws-java-sdk-sts module must be on the class path., 
com.amazonaws.auth.profile.ProfileCredentialsProvider@4eeab0ba: profile file cannot be null,
com.amazonaws.auth.EC2ContainerCredentialsProviderWrapper@19104bd5: Failed to connect to service endpoint: ]. All previously activated executables from this batch will be discarded.
```

__Expected Behavior__

camunda-connectors should be able to assume the role through service account using WebIdentity and token file.

__Environment__

- Node OS: Bottlerocket OS 1.27.1 (aws-k8s-1.30)
- Camunda-connectors version: [e.g. 8.6.4 (self-managed)]
