### ISSUE TITLE
[Connectors probe] Add a proper liveness probe

### ISSUE THREAD

**Issue by mathias-vandaele** [camunda/connectors#4404]
__What should we do?__

We should have a proper management of liveness probe. We currently use `/actuator/health/readiness` as a liveness probe, which is not optimal.

In our code we have

```
    livenessProbe:
      enabled: true
      # Force restart if not ready
      probePath: /actuator/health/readiness
```

We should add a liveness endpoint, the default or a custom one (if possible)

__Why should we do it?__

Because connectors pod is restarted often, most likely because one bad call to operate can make our app unhealthy
