### ISSUE TITLE
Connectors 8.7.2 - FileSystemException: /home/camunda: Read-only file system

### ISSUE THREAD

**Issue by igor-msk** [camunda/connectors#4819]
__Describe the Bug__
After upgrading to 8.7.2 from 8.6.X I constantly see the following errors in connectors log
java.nio.file.FileSystemException: /home/camunda: Read-only file system.
Full log trace 

[connectors_log_trace.txt](https://github.com/user-attachments/files/20503930/connectors_log_trace.txt)

is attached

__Steps to Reproduce__
Run connectors 8.7.2 with default configuration in kuber

The error was gone with the following config
```
connectors:
  containerSecurityContext:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
```
or by 
```
extraVolumes:
  - name: homecamunda
    emptyDir: {}
  extraVolumeMounts:
  - name: homecamunda
    mountPath: /home/camunda
```

__Expected Behavior__
no errors when
```
connectors:
  containerSecurityContext:
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1001
```

__Environment__
- Camunda version: 8.7.2 self-managed
