### ISSUE TITLE
Connector remapping configuration

### ISSUE THREAD

**Issue by chillleader** [camunda/connectors#518]
## Description

We would like to introduce the new configuration properties support in the connector runtime to target the following use-cases.

### 1. Disable connectors

I have a process application that bundles some Camunda connectors. When the application starts, all connectors start as well. In specific cases, I want to disable one or all connectors in the configuration. Currently, it is not possible to disable a connector. 

For other job workers, I can disable them via config:

```
zeebe.client.worker.override.foo.enabled=false
```

Or, by defining a bean that implements `ZeebeWorkerValueCustomizer`.

But both methods don't work for connectors.

### 2. Connector type remapping

It would be useful to allow overriding/remapping connector types. This issue occurs e.g. when running a self-hosted connector runtime that connects to the Camunda 8 SaaS cluster. As the two connector runtimes are unaware of each other's presence, it is impossible to configure which runtime should receive a job for a certain connector. If there are Kafka connectors running in both runtimes, both will occasionally receive jobs from Zeebe, but sometimes we want to use the self-managed runtime only e.g. to access the Kafka cluster on-premises.

It would be nice to allow to redefine the types registered for each connector, e.g. change the default one from `io.camunda:connector-kafka:1` to `com.mycompany:connector-kafka:1`, or even allow both.

## Proposal

Introduce a connector configuration. It should cover both remapping and disabling and may look like this:
```
camunda.connector:
  outbound:
    KAFKA:
      enanled: false
    RABBITMQ:
      enabled: true
      types:
        - io.camunda:connector-rabbitmq:1
        - com.mycompany:connector-rabbitmq:1
```
