### ISSUE TITLE
Connector component

### ISSUE THREAD

**Issue by Touchteng** [camunda/connectors#5606]
Hi everyone!

I am facing the issue on Connector component while deployment in Argo CD using Helm Chart.
The package I downloaded from GitHub Camunda platform 8.7 

"Description:
Failed to bind properties under 'camunda.client.zeebe' to io.camunda.zeebe.spring.client.properties.common.ZeebeClientProperties:
    Property: camunda.client.zeebe.grpc-address
    Value: "http://camunda-8.7-staging-zeebe-gateway:26500"
    Origin: "camunda.client.zeebe.grpc-address" from property source "zeebe-client-legacy-overrides.properties"
    Reason: java.lang.IllegalArgumentException: grpcAddress must be an absolute URI
Action:
Update your application's configuration"

Thanks,

**Comment by johnBgood** [comment]
Hey, 
Thank you for reaching out. 
Did you try using the [configuration provided](https://docs.camunda.io/docs/8.7/self-managed/connectors-deployment/connectors-configuration/) in the docs?

Especially this part (change the values):

```yaml
camunda:
  client:
    mode: self-managed
    zeebe:
      grpc-address: http://localhost:26500
      rest-address: http://localhost:8080
```

If that doesn't help, could you share the Connectors configuration you used?

Thank you,
Jonathan
